vf_blog:
    resource: "@VFBlogBundle/Resources/config/routing.yml"
    prefix:   /

vf_booking:
    resource: "@VFBookingBundle/Resources/config/routing.yml"
    prefix:   /

vf_core:
    resource: "@VFCoreBundle/Resources/config/routing.yml"
    prefix:   /

vf_user:
    resource: "@VFUserBundle/Resources/config/routing.yml"
    prefix:   /

vf_crotoy:
    resource: "@VFCrotoyBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile