<?php

namespace VF\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepository extends EntityRepository
{
}
